### PR TITLE
feat(windows): Add the implementation and examples of the host object for the Windows system.

### LINKED ISSUE #454: feat: synchronous communication between webview and rust
Tauri has a lot of functions in its Js API that can and should be synchronous instead of async, for example the `homeDir` function in tauri's `path` module. Synchronous communication can also help boost the performance since it doesn't include any serializations (I think).

- Webview2:
  - [`AddHostObjectToScript()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=webview2-dotnet-1.0.1054.31) exposes full host objects to Js which can be used asynchronously and synchronously. But it's blocked by https://github.com/microsoft/windows-rs/issues/1094. [Here](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/winrt-js-conversion) are the types it can support.
  - [`CreateSharedBuffer`](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2environment?view=webview2-winrt-1.0.1661.34#createsharedbuffer) creates an ArrayBuffer that can be used by webview and rust. But both processes must close it manually to release memory so that it can be error-prone.
- WkWebview:
  - [`didReceiveScriptMessage`](https://developer.apple.com/documentation/webkit/wkscriptmessagehandlerwithreply/3585111-usercontentcontroller?language=objc) can also receive and return certain types.
- Webkit2gtk:
  - [`webkit_user_content_manager_register_script_message_handler_with_reply`](https://webkitgtk.org/reference/webkit2gtk/stable/signal.UserContentManager.script-message-with-reply-received.html) can create and return fully defined JS value.

**Would you assign yourself to implement this feature?**
- [X] Yes (partially)
- [ ] No

### PR DESCRIPTION
**Pull request by defims**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Checklist
- [x] This PR will resolve #454 
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/wry/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary
- [ ] It can be built on all targets and pass CI/CD.

### Other information
My project [wvwasi](https://github.com/defims/wvwasi) needs synchronous methods, so I implemented add_host_object_to_script for Windows in this pull request.

### CODE REVIEW

**Comment by wusyong** [comment]
I have tried to add this feature before, but this is a pretty dangerous one IHMO. And it only supports Windows.
However, I saw many other issues are requesting this feature: https://github.com/tauri-apps/wry/issues/1110
So the best approach to add this is probably move this to platform specific trait.

**Comment by defims** [comment]
> I have tried to add this feature before, but this is a pretty dangerous one IHMO. And it only supports Windows. However, I saw many other issues are requesting this feature: #1110 So the best approach to add this is probably move this to platform specific trait.

@wusyong I agree, so I put the method in [WebViewExtWindows](https://github.com/tauri-apps/wry/pull/1109/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759L1387), and I don't do any additional packaging, just leave the creation of hostObject to the user, and they will handle the risks on their own.

**Comment by defims** [comment]
@wusyong I don't know how to fix that two error checks. Would you help me fix it or just ignore it?

**Comment by defims** [comment]
There are many factors to consider when merging the dev trunk, especially the core communication parts. If someone needs to use this method temporarily, they can use [wvwasi-wry](https://crates.io/crates/wvwasi-wry). For production use, it is still recommended to use the version after merging to the dev trunk.

**Comment by wusyong** [comment]
@defims  Could you format the code at least? The doc CI seems broken at the moment. #1117 is the tracking issue.
I can merge this one once other CI pipelines are passed.

**Comment by defims** [comment]
> @defims Could you format the code at least? The doc CI seems broken at the moment. #1117 is the tracking issue. I can merge this one once other CI pipelines are passed.

@wusyong Sorry, I didn't notice that one of them was a formatting issue. Of course, I formatted it and submitted it. Please check it again.😊

**Review by dklassic — APPROVED** [review]

**Comment by dklassic** [comment]
Hey @defims thanks for contributing! Though we have enforced commit signing so I'll need you to sign your commit before we can merge it.

**Comment by defims** [comment]
> Hey @defims thanks for contributing! Though we have enforced commit signing so I'll need you to sign your commit before we can merge it.

@dklassic My pleasure. I have resubmitted it and signed the commit. Please check it again.😊

**Comment by amrbashir** [comment]
Looks like this PR is only exposing APIs that can be accessed through `webview.controller` and I don't see any value in adding it here tbh.

**Comment by defims** [comment]
> Looks like this PR is only exposing APIs that can be accessed through `webview.controller` and I don't see any value in adding it here tbh.

@amrbashir Thank you for your review.

HostObject mainly provides synchronous methods. Existing methods such as synchronous XHR are already [restricted to worker](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest_API/Synchronous_and_Asynchronous_Requests#synchronous_request) in mainstream browsers, mainly due to the concern of blocking the rendering process.

However, the situation is different in the webview. Webview is mainly used on the device, which is more controllable. In some scenarios, such as some synchronous libraries heavily dependent on C/C++, it is not realistic to rewrite the library completely. In this case, synchronous methods are more important than blocking the rendering process.

There are other synchronous scenarios, which are not listed here. Of course, these scenarios are rare, so I personally do not recommend using synchronous methods as the main communication method.

For this reason, I have not wrapped related methods too much. Instead, I only expose basic APIs on `WebViewExtWindows`. This allows us to cover a small number of applicable scenarios with the lowest maintenance cost. We also do not need to consider the burden of use too much, as users can manage the burden themselves.

WKWebView and WebKitGTK currently do not have similar APIs. The cost of simulating them with existing interfaces is too high, so they have not been added yet. If the relevant API documentation is provided, I will be happy to add them and encapsulate them into a unified interface.

**Comment by defims** [comment]
Same goes for https://github.com/tauri-apps/wry/pull/1115

**Pull request closed without merging**
