### PR TITLE
refactor: add `#[non_exhaustive]` attributes to enums

### PR DESCRIPTION
**Pull request by lucasfernog**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [ ] No

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by lucasfernog** [comment]
Note that this is a breaking change so it'll release `wry` v0.11. If you wanna release again soon, maybe this PR shouldn't be merged.

**Review by wusyong — APPROVED** [review]

**Comment by wusyong** [comment]
If tauri doesn't need it at the moment, I suppose we could keep the PR until next release.

**Comment by lucasfernog** [comment]
Yeah, I only did this to prevent accidental breaking changes in the future.

**Comment by lemarier** [comment]
@wusyong should we `minor` bump wry too?

**Pull request merged**
