### PR TITLE
Update windows-rs to 0.37.0 and webview2-com to 0.16.0 to match

### PR DESCRIPTION
**Pull request by wravery**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

Starting as a draft PR because I still have a patch override in `Cargo.toml` to pull the matching version of `tao` in https://github.com/tauri-apps/tao/pull/400.

As in that PR, updating to this version of `windows-rs` raises the MSRV on Windows to 1.61, which was just released to the `stable` channel today. 🎉

### CODE REVIEW

**Review by amrbashir — DISMISSED** [review]

**Comment by wravery** [comment]
The reason the last CI failed is just that I removed the `[patch.crates-io]` table in https://github.com/tauri-apps/wry/pull/592/commits/309fffa76734c2ac32e87f07c1fd43472bd265a1 to prepare this PR for merging. Once https://github.com/tauri-apps/tao/pull/400 is merged and a new version of `tao` is published, CI for this PR should start passing again.

**Comment by wravery** [comment]
The changes in https://github.com/tauri-apps/wry/pull/592/commits/b63db59bb2361c3bc30fa0a469046cab9826a10e and https://github.com/tauri-apps/wry/pull/592/commits/181a8272b16120b0b5111914180964a6b267f7ed should make it so the next time we update `windows`, we don't need to stage the PRs like this. Once `tao` no longer requires a matching `HWND` type (in https://github.com/tauri-apps/tao/commit/793c1e6515988f1bbd17aac955a11a26c805cdf3) and `wry` includes all of the features it needs from `windows` instead of inheriting some of them from `tao`, they should be able to build with independent versions of `windows`.

**Comment by wravery** [comment]
I undid the changes in https://github.com/tauri-apps/wry/pull/592/commits/9855a8510bd787555b3041e9b82b44af397ba679 (bumping the MSRV for `wry` on all platforms) and documented it in the change log: https://github.com/tauri-apps/wry/pull/592/commits/6e4e0ee5100d9879688487a2397512497e1fe0c2.

**Review by amrbashir — DISMISSED** [review]

**Comment by wusyong** [comment]
@wravery  We just published tao 0.9!

**Comment by lucasfernog** [comment]
The change looks ok, but the file drop path reader is wrong. The `DragQueryFileW(hdrop, i, &mut path_buf)` call is accessing random memory it seems. cc @wravery

**Comment by wravery** [comment]
> The change looks ok, but the file drop path reader is wrong. The `DragQueryFileW(hdrop, i, &mut path_buf)` call is accessing random memory it seems. cc @wravery

Ah, I think this is because it's not actually sizing the `Vec` until after the call (trying to avoid initializing the out-param). The signature change where it takes a slice instead of a pointer + length means that the slice is length 0.

It should probably pass `std::mem::transmute(path_buf.spare_capacity_mut())` instead of `&mut path_buf`. I need to check if the equivalent pattern exists anywhere else in here or in the corresponding `tao` changes.

**Comment by lucasfernog** [comment]
I can confirm the `std::mem::transmute(path_buf.spare_capacity_mut())` change fixes it.

**Review by lucasfernog — DISMISSED** [review]

**Comment by wravery** [comment]
> I need to check if the equivalent pattern exists anywhere else in here or in the corresponding `tao` changes.

I started a [bugfix PR](https://github.com/tauri-apps/tao/pull/401) in `tao` for the same issue. Other than that, it looks like there are no more references to `with_capacity` -> `&mut slice` in either project, so I think it was just this one line that was affected in each of them.

**Pull request merged**
