### PR TITLE
refactor: change custom protocol handler input to an owned Request

### PR DESCRIPTION
**Pull request by lucasfernog**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### Checklist
- [ ] This PR will resolve #___
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/wry/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary
- [ ] It can be built on all targets and pass CI/CD.

### CODE REVIEW

**Comment by wusyong** [comment]
Can we take this chance to refactor to `Request<Cow<'static, [u8]>>`?
This could reduce some vector allocations.

**Comment by lucasfernog** [comment]
@wusyong I couldn't really see the improvement, the request body will never be an static [u8].

**Comment by wusyong** [comment]
Or could it be `Cow<'_, [u8]>`? Because I know many of original types can be deref to u8 slice.

**Comment by amrbashir** [comment]
Closing since this change has been merged in https://github.com/tauri-apps/wry/pull/1017

**Pull request closed without merging**
