### PR TITLE
feat(windows) add print_to method in wry

### PR DESCRIPTION
**Pull request by huangmingg**
First PR to get the ball rolling for https://github.com/tauri-apps/plugins-workspace/issues/293

### CODE REVIEW

**Comment by amrbashir** [comment]
I feel like advanced printing functionality could be left out of `wry`, since tauri has [`with_webview`](https://docs.rs/tauri/latest/tauri/window/struct.Window.html#method.with_webview) and could be used to implement the needed APIs in the plugin rather directly in `wry`.

cc @wusyong @lucasfernog

**Comment by wusyong** [comment]
I prefer to use [with_webview](https://docs.rs/tauri/latest/tauri/window/struct.Window.html#method.with_webview) too. And this one seems to be platform specific.

**Comment by huangmingg** [comment]
What are the advantages of pushing this feature downstream to `tauri`? The ability to silent print from a webview sounds like the responsibility of `wry`.

It also seems using `with_webview ` will require exposing more fields downstream to tauri, such as ICoreWebView2Environment of windows to create the printer setting.

**Comment by amrbashir** [comment]
> What are the advantages of pushing this feature downstream to `tauri`? The ability to silent print from a webview sounds like the responsibility of `wry`.

advanced printing functionality doesn't sound like a thing that should be maintained in `wry`, it should instead be in its own plugin so it is easier to maintain both projects and easier to contribute to.

> It also seems using `with_webview ` will require exposing more fields downstream to tauri, such as ICoreWebView2Environment of windows to create the printer setting.

You can still get the webview2 environment though the controller.

**Comment by huangmingg** [comment]
How can i get the webview2 environment via the controller?

**Comment by FabianLars** [comment]
It's on the webview, not the controller but you can use this method to get it: https://docs.rs/webview2-com/latest/webview2_com/Microsoft/Web/WebView2/Win32/trait.ICoreWebView2_2_Impl.html#tymethod.Environment

**Comment by amrbashir** [comment]
yes you can get ICoreWebview2 from controller and get the environment from ICoreWebview2

**Comment by lucasfernog** [comment]
I agree this should be left out of wry, at least until it is supported on more platforms

**Pull request closed without merging**
