### PR TITLE
Added WebView::load_html

### PR DESCRIPTION
**Pull request by VictorKoenders**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Checklist
- [ ] This PR will resolve #___
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/wry/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary
- [x] It can be built on all targets and pass CI/CD.

### Other information

There is currently `WebViewBuilder::with_html` but there is no way to load in HTML after the `WebView` has been constructed. This is an attempt at adding that.

I have only tested this on Windows right now. The other platforms still need testing / fixing. Please chip in if you can test or have feedback.

### CODE REVIEW

**Comment by dklassic** [comment]
Tested on Android using cargo-mobile2, seems to be working properly.

**Comment by VictorKoenders** [comment]
Rebased onto `dev`

**Comment by pewsheen** [comment]
Also tested in Windows/macOS/ubuntu

**Review by amrbashir — APPROVED** [review]

**Comment by amrbashir** [comment]
@VictorKoenders looks like you didn't sign your commits and I can't merge the PR unless they are signed. You need to setup [commit signing](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits), then you can sign past commit like [this](https://superuser.com/questions/397149/can-you-gpg-sign-old-commits/1123928#1123928) for example.

**Comment by just-be-dev** [comment]
I didn't notice this PR. I re-implemented this in #1368 and it was released in [0.45.0](https://github.com/tauri-apps/wry/blob/dev/CHANGELOG.md#0450).

**Comment by amrbashir** [comment]
This totally fell out of my radar, thanks @VictorKoenders for the PR though and apologies for keeping it this long

**Pull request closed without merging**
