### PR TITLE
fix: disalbe bounce option for macos, closes #557

### LINKED ISSUE #557: Set scroll bounce on WKWebView
MacOS has this bounce effect when you scroll. I would like to disable it. I think it is `webView.scrollView.bounces = NO;`. I think the default should be `false`, like it is in for example Electron.

**Describe alternatives you've considered**
Tried to do this in CSS, but I couldn't find a working solution so far. I've read that adding a certain class to all of the elements in the DOM fixes it, or applying some JS, but it is a real hassle. Most people suggest just setting the bounces property to NO.

**Would you assign yourself to implement this feature?**
- [ ] Yes
- [x] No

**Additional context**
None

### PR DESCRIPTION
**Pull request by yuta24**
I fixed https://github.com/tauri-apps/wry/issues/557.

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

For compatibility, bounce is On by default.

### CODE REVIEW

**Comment by probablykasper** [comment]
Does bouncing mean rubber band scrolling?

**Comment by nothingismagick** [comment]
I thought there was a CSS way to do this too...
```css
body {
  height: 100%;
  padding: 0;
  overflow: auto;
  margin: 0;
  -webkit-overflow-scrolling: touch;
}
```

**Comment by nothingismagick** [comment]
or this (if you manage scrolling internally in the layout):

```css
body {
  position: fixed;
}
```

**Comment by wusyong** [comment]
Thanks you for the PR! But I dont think this will work.
WkWebview on macOS doesn't have scroll view somehow.
https://stackoverflow.com/questions/39929552/disable-bounce-scrolling-for-wkwebview-in-macos

Did it solve the issue on your side?

**Comment by yuta24** [comment]
> Does bouncing mean rubber band scrolling?

Yes, If webview's content size is over the window size, rubber band scrolling is good. But, the app using wry always enable rubber band scrolling. I thought it would be better if wry had an enable/disable option.

> I thought there was a CSS way to do this too...
> body {
>  height: 100%;
>  padding: 0;
>  overflow: auto;
>  margin: 0;
>  -webkit-overflow-scrolling: touch;
> }

It wasn't working on my project.

> WkWebview on macOS doesn't have scroll view somehow.
> https://stackoverflow.com/questions/39929552/disable-bounce-scrolling-for-wkwebview-in-macos
> 
> Did it solve the issue on your side?

Sorry. This PR's solution works in specific situations. I'll close this PR.

**Comment by nothingismagick** [comment]
don't be hasty - Tauri has become a collection of edge-cases, and some might find it useful as an option.

**Comment by probablykasper** [comment]
I get horizontal rubber band scrolling, and it's always an annoyance with no benefit. The CSS above doesn't fix it, but the PR does. `-webkit-overflow-scrolling` isn't supported for me on macOS 10.15.

Is there any reason to actually keep `bounce` on by default?

**Comment by evoactivity** [comment]
For future googlers, you also need to disable overflow on the html element, eg

```css
html {
  height: 100vh;
  width: 100vw;
  overflow: hidden;
}

body {
  height: 100%;
  padding: 0;
  overflow: auto;
  margin: 0;
  -webkit-overflow-scrolling: touch;
}
```

**Pull request closed without merging**
