### PR TITLE
feat/add-window.close()

### PR DESCRIPTION
**Pull request by amrbashir**

### CODE REVIEW

**Comment by nklayman** [comment]
Do you want to put the example updates here that you accidentally put in the other one?

**Comment by amrbashir** [comment]
sure

**Comment by nklayman** [comment]
Wait my bad I din't mean those, I thought you added a close_window demo to the examples and accidentally put that in the other fix examples PR. I totally got confused, these should be separate PRs :facepalm:. Sorry for the trouble :disappointed:

**Comment by amrbashir** [comment]
I was kinda confused too, a simple rebase and it will be fine, dw.

**Comment by nklayman** [comment]
Okay I'm gonna stop doing things now and leave it up to @wusyong :joy:.

**Pull request merged**
