### PR TITLE
Revert "fix(macos): check WKURLSchemeTask is valid before using"

### PR DESCRIPTION
**Pull request by wusyong**
Reverts tauri-apps/wry#1282

Didn't realize there's another slimilar one in discussion.

### CODE REVIEW

**Review by jason-crabnebula — APPROVED** [review]

**Review by pewsheen — APPROVED** [review]

**Comment by FabianLars** [comment]
to be fair though, imo jason's solution was better because it didn't use so much objc 😂

**Comment by pewsheen** [comment]
> to be fair though, imo jason's solution was better because it didn't use so much objc 😂

I was about to ask for your opinion lol

This still crashes in some circumstances, so we want to revert it first and try something else.

**Comment by FabianLars** [comment]
hmm, that's unfortunate. Did you check if the community pr also crashes in the same context?

**Comment by pewsheen** [comment]
> hmm, that's unfortunate. Did you check if the community pr also crashes in the same context?

Community PR works, and I was testing the example that PR provided.
It looks like the `task` will be released even inside the didResponse method. Retain `task` until the response closure ends would fix it. I'll reopen the PR again with the fix.

update:
Community PR does not work for the issue on tauri

**Pull request merged**
