### PR TITLE
fix: fix all clippy warnings and enable clippy on CI

### PR DESCRIPTION
**Pull request by rhysd**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Checklist
- [ ] This PR will resolve #___
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/wry/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary
- [ ] It can be built on all targets and pass CI/CD.

### Other information

This PR fixes all warnings reported by clippy on my local machine. I confirmed all examples fixed by this PR on my local machine manually.

### CODE REVIEW

**Comment by rhysd** [comment]
Clippy passed on CI. https://github.com/tauri-apps/wry/actions/runs/4915685028/jobs/8778465188?pr=953

**Comment by FabianLars** [comment]
Thanks for contributing!

i think we should add (back) a caching step to that workflow now (basically just a `- uses: Swatinem/rust-cache@v2` step)

**Comment by rhysd** [comment]
Thanks for the point. I added the action to the workflow at 6a90182.

**Review by FabianLars — APPROVED** [review]
i hope clippy is sure about the `drop()` change 😅

**Comment by rhysd** [comment]
[`drop_in_place`](https://doc.rust-lang.org/std/ptr/fn.drop_in_place.html) returns `()`. So

```rust
drop(self.download_delegate.drop_in_place());
```

is exactly the same as

```rust
self.download_delegate.drop_in_place();
drop(());
```

And `drop(())` does nothing. We can safely remove the `drop()` call.

**Pull request merged**
