### PR TITLE
Fix: 276 - Add ability to set custom User Agent

### PR DESCRIPTION
**Pull request by aditsachde**
It'd be useful to set a custom UA for identifying desktop apps. Additionally, some sites require UA spoofing to work.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- x ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
- The Win32 Webview2 API does not support overriding the user agent yet. 
- The linux and winrt implementations still have to be tested.
- @shirakaba mentioned in #276 that ideally it should be possible to update the user agent on the fly. This makes sense, but I do not know the best way to implement this functionality.
- I still need to add a change file.

### CODE REVIEW

**Comment by lemarier** [comment]
Update;

It works fine on macOS and Linux. 

Windows do not support it in the current version and require `webview2-1.0.864.35` +.

https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings2?view=webview2-1.0.864.35

We are running `webview2-1.0.818.41`
https://github.com/sopium/webview2/tree/master/webview2-sys

**Comment by ghost** [comment]
adding a custom `user-agent` is actually a requirement for some servers such as Jira, which blocks requests from certain user-agents and so you must spoof yours

How can I test this PR out? Can I install it as a version with cargo?

**Comment by lemarier** [comment]
@wusyong what you think if we merge it and keep windows noop and document it.

**Comment by wusyong** [comment]
It's possible to do it on win32. Just need to update the `webview2` crate.
I'll find some time open a PR there
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings2?view=webview2-1.0.902.49

**Comment by lemarier** [comment]
> It's possible to do it on win32. Just need to update the `webview2` crate.
> I'll find some time open a PR there
> https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings2?view=webview2-1.0.902.49

The binding are not updated
https://github.com/sopium/webview2/tree/master/webview2-sys/Microsoft.Web.WebView2.1.0.818.41

**Comment by wusyong** [comment]
That version still has method to set user agent. 
If this is in hurry, I can merge this first and open the PR there later.

**Comment by lemarier** [comment]
> That version still has method to set user agent.
> If this is in hurry, I can merge this first and open the PR there later.

it's not urgent, but the current binding does NOT expose it, it's been introduced in 1.0.864.35 who is 2 release after our current binding version. 

Also sopium bindings, hasn't been updated since April so it's something we should consider. 
Should we want to keep going like this?

PS; I started to work on sopium PR to update to latest version but didn't had the time to finish.

**Comment by nothingismagick** [comment]
fork the bindings? april -> aug is a sign of scary bus factor.

**Comment by lemarier** [comment]
> fork the bindings? april -> aug is a sign of scary bus factor.

https://github.com/sopium/webview2/tree/master/webview2-sys

**Comment by nothingismagick** [comment]
https://github.com/sopium/webview2/commit/73732007c24625d2c44f2e9bd33d13e36391d26e

It's not even using modern rust in the CI.

**Comment by wusyong** [comment]
I could help updating the crate.
Tbh the version is not really that outdated imho.
This crate really helps us a lot, I'll try my best to contribute first.
If the author is too busy, we could make a soft fork after it (and switch back once there's updates).

**Comment by nothingismagick** [comment]
> I could help updating the crate.
> Tbh the version is not really that outdated imho.
> This crate really helps us a lot, I'll try my best to contribute first.
> If the author is too busy, we could make a soft fork after it (and switch back once there's updates).

I am for a soft fork.

**Comment by lemarier** [comment]
> I could help updating the crate.
> Tbh the version is not really that outdated imho.
> This crate really helps us a lot, I'll try my best to contribute first.
> If the author is too busy, we could make a soft fork after it (and switch back once there's updates).

Please see https://github.com/tauri-apps/tauri/issues/2570#issuecomment-913143578

That’s why I want us to keep the binding to the latest version.
MS is moving fast, we need to follow.

**Comment by amrbashir** [comment]
Superseded by #464 

Thanks for your contribution.

**Pull request closed without merging**
