### PR TITLE
fix(macOS): Printing (#235)

### PR DESCRIPTION
**Pull request by lemarier**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
It prints!

### CODE REVIEW

**Comment by wusyong** [comment]
I can confirm webkit2gtk has similar API, but webview2 doesn't have it yet.
The workaround on Windows might need to use `window.print()` on js. wdyt?

**Comment by lemarier** [comment]
> I can confirm webkit2gtk has similar API, but webview2 doesn't have it yet.
> The workaround on Windows might need to use `window.print()` on js. wdyt?

Did the window.print work on windows/linux?  (I didnt tested) — Because on mac we had a blank page.

**Comment by wusyong** [comment]
This is what it looks like on Linux
image
And here is the generated dpf file
image
(will update windows in next comment)

**Comment by wusyong** [comment]
And here's windows
圖片
And generated pdf
圖片

So it seems fine on both. But I think it's better we still use webkitgtk api on Linux.

**Review by wusyong — APPROVED** [review]

**Pull request merged**
