### PR TITLE
feat: re-export raw-window-handle crate

### LINKED ISSUE #1066: Make `HasRawWindowHandle` public
**Is your feature request related to a problem? Please describe.**

As [README.md](https://github.com/tauri-apps/wry#readme) states, `HasRawWindowHandle` is an important part of public API of this crate.

> The webview requires a running event loop and a window type that implements HasWindowHandle, or a gtk container widget if you need to support X11 and Wayland

However, currently wry doesn't re-export the trait. This means that, if users want to use the trait, they need to manage `raw-window-handle` crate as their dependency keeping the version compatible with wry's `raw-window-handle` dependency.

The latest version of [raw-window-handle](https://crates.io/crates/raw-window-handle) crate is v0.6.0. And wry depends on v0.5. So users can easily install wrong version of the crate by `cargo add` and will face a weird error. Though they are the same name, traits from different versions of same crate are handled as completely different traits.

**Describe the solution you'd like**

To avoid managing the dependency separately in two places, it is a good idea to re-export wry's `HasRawWindowHandle` trait as wry re-exported `tao` as `wry::application` previously.

**Describe alternatives you've considered**

Keep hiding the trait would be an option as strategy of maintenance though I can't come up with any benefits.

**Would you want to assign yourself to implement this feature?**
- [x] Yes
- [ ] No

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by rhysd**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Checklist
- [x] This PR will resolve #1066
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/wry/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary
- [x] It can be built on all targets and pass CI/CD.

### Other information

I didn't add a file under `.changes` directory because this change can be amended to changes of #1041.

### CODE REVIEW

**Comment by amrbashir** [comment]
I would prefer to re-export the whole `raw-window-handle` crate.

**Comment by rhysd** [comment]
That also makes sense to me. Do you have any suggestion about module name?

- `wry::raw_window_handle`
- `wry::rwh`

**Comment by amrbashir** [comment]
`raw_window_handle` is fine

**Comment by rhysd** [comment]
Sure. I will do the change tonight.

**Comment by rhysd** [comment]
@amrbashir I updated this branch based on your comments.

**Review by wusyong — APPROVED** [review]

**Pull request merged**
