### PR TITLE
feat(android): support navigation handler (#972)

### LINKED ISSUE #972: [feat] support navigation handler on android
**Is your feature request related to a problem? Please describe.**
I would like to be able to apply a navigation handler to android clients.

**Describe the solution you'd like**
Add support for setting the navigation handler on android.

**Describe alternatives you've considered**
None, this is a feature parity request.

**Would you want to assign yourself to implement this feature?**
- [x] Yes
- [ ] No

**Additional context**
This should be pretty straight forward.

### PR DESCRIPTION
**Pull request by jhutchins**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Checklist
- [x] This PR will resolve #972 
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/wry/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary
- [x] It can be built on all targets and pass CI/CD.

### CODE REVIEW

**Comment by lucasfernog** [comment]
I can't test this right now but the code looks amazing, nice work!

**Review by lucasfernog — APPROVED** [review]
Works well. The only problem I see is navigations triggered by [loadUrl](https://developer.android.com/reference/android/webkit/WebView#loadUrl(java.lang.String)) does not trigger the [shouldOverrideUrlLoading](https://developer.android.com/reference/android/webkit/WebViewClient#shouldOverrideUrlLoading(android.webkit.WebView,%20android.webkit.WebResourceRequest)) callback. Seems like a limitation on Android itself, only JavaScript navigations trigger it. Of course we could change `loadUrl(url)` calls with `evaluateJavascript("window.location.href = `$url`", null)`, but that does not work for the `loadUrl(url, additionalHttpHeaders)` overload.

**Comment by jhutchins** [comment]
@lucasfernog is there currently a mechanism to call `loadUrl`? Regardless, if you want that I can absolutely make that work, wouldn't even be difficult.

**Comment by lucasfernog** [comment]
Right we can implement that manually. I think it's valuable for cross platform compatibility. What do you think @wusyong ?

**Comment by lucasfernog** [comment]
And yeah we're overriding the loadUrl functions on the RustWebview Kotlin class.

**Pull request merged**
