### PR TITLE
fix(deps): Use less specific version for once_cell

### PR DESCRIPTION
**Pull request by FabianLars**
ref: https://discord.com/channels/616186924390023171/1074435079964725329

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Checklist
- [ ] This PR will resolve #___
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/wry/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary
- [x] It can be built on all targets and pass CI/CD.

### CODE REVIEW

**Comment by amrbashir** [comment]
we need to be careful with this one, once_cell author has bumped MSRV before in a patch version? don't remember exactly and it is unlikely that once_cell will bump MSRV again anytime soon but we should still be careful

**Comment by FabianLars** [comment]
this is actually why i opened this pr, they increased the MSRV in 1.15 and there are crates locking it to 1.14 because of that. So us setting a _minimum_ version this high is not good for compatibility. ("this high" was meant for the dev branch where we just always merge the latest renovate pr. it's on 1.17 right now)

**Comment by amrbashir** [comment]
So setting it to `1` would allow cargo to choose a compatible version?

**Comment by FabianLars** [comment]
yeah, then cargo would be allowed to just use 1.14 for all deps for example.

`1` is basically the same as `1.0` (or `^1.0` in npm land) just without renovate bothering us on each new minor version.

iirc we started adding less specific versions back when someone reported that they had to pin tokio to a slightly lower version but we always merged the latest renovate pr into tauri.

But yes, this will not prevent msrv bumps. cargo does not factor that in unfortunately.

**Pull request merged**
