### PR TITLE
Better mime handling. This time for real

### PR DESCRIPTION
**Pull request by wusyong**

### CODE REVIEW

**Review by nothingismagick — APPROVED** [review]
Tested winit example on macos m1

**Comment by lucasfernog** [comment]
We should probably move this to a separate function in the future. But this is good enough for now.

**Review by lucasfernog — APPROVED** [review]

**Comment by nothingismagick** [comment]
> We should probably move this to a separate function in the future. But this is good enough for now.

Do you mean since it is literally exactly the same code repetition in three files?

**Comment by lucasfernog** [comment]
> > We should probably move this to a separate function in the future. But this is good enough for now.
> 
> Do you mean since it is literally exactly the same code repetition in three files?

Yeah :)

**Review by nklayman — APPROVED** [review]
Looks good but I do think this should be put in a separate function at some point, it'll be a good PR for new contributors to Wry.

**Pull request merged**
