### PR TITLE
fix set_decorations

### PR DESCRIPTION
**Pull request by jussiniinikoski**

### CODE REVIEW

**Comment by nothingismagick** [comment]
Thanks for noticing this! I just reviewed the file, and it seems there is one more place where its wrong:
```rust
    pub fn set_transparent(&self, resizable: bool) -> Result<()> {
        self.proxy.send_message(Message::Window(
            self.id,
            WindowMessage::SetResizable(resizable),
        ))
    }
```

**Comment by jussiniinikoski** [comment]
Looks like setting transparency is currently only implemented using attributes..

**Comment by jussiniinikoski** [comment]
I could try to fix this, perhaps a separate PR?

**Comment by nothingismagick** [comment]
Let's wait for @wusyong to weigh in here.

**Comment by wusyong** [comment]
@jussiniinikoski another PR is good to me. The actual working transparent option has to wait for next version anyway.

**Review by wusyong — APPROVED** [review]

**Comment by wusyong** [comment]
@jussiniinikoski Sorry I forgot to tell you more context. Right now the transparent option can only be set on initialization so it shouldn't have a method in the proxy. We should remove those lines actually.

**Comment by jussiniinikoski** [comment]
Ok, thanks for info.

**Pull request merged**
