### PR TITLE
feat: expose `eval` method

### PR DESCRIPTION
**Pull request by geieredgar**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
This allows executing javascript code without having to use the `mpsc::channel` and helps to simplify `handle_event_loop` in `tauri-runtime-wry` (see tauri-apps/tauri#1962).

### CODE REVIEW

**Comment by wusyong** [comment]
The problem is this method is not thread-safe. It should be called on the main thread only.
Mpsc channel could help you send the script on any thread.
I think one workaround is we could call `evaluate_script` immediately after `dispatch_script` if it's on main thread (ie. in the event loop)
@lucasfernog wdyt?

**Comment by geieredgar** [comment]
Yes, calling `evaluate_script` immediately after `dispatch_script` is also what I did in my PR [tauri-apps/tauri#1963](https://github.com/tauri-apps/tauri/pull/1963) to fix [tauri-apps/tauri#1962](https://github.com/tauri-apps/tauri/issues/1962). I just think that solution is a bit ugly, which is why I opened this PR. In my opinion it would be a lot cleaner if wry did only provide the `eval` method and no `evaluate_script`, `dispatch_script` and `Dispatcher`, with a doc comment stating that `eval` should only be called on the main thread (I think this information should also be added to `evaluate_script`) and maybe a hint that users could use channels if they want to send scripts from any thread. I actually think that using the `EventLoopProxy` to send scripts from any thread is a better solution than using an mpsc channel because it always wakes up the event loop, which would not happen if a script is send via `Dispatcher`, where we cannot call `evaluate_script` afterwards and would have to send a message to the event loop anyway.

**Comment by wusyong** [comment]
Yeah, I think we could do that. If @lucasfernog also agrees (since tauri will need some custom event on EventLoopProxy), let's remove the dispatcher and all its related methods and expose this instead.

**Comment by geieredgar** [comment]
FYI, `tauri` already uses a `WebviewMessage::EvaluateScript` custom event and AFAICT doesn't use the `Dispatcher`.

**Comment by geieredgar** [comment]
Closed in favor of #291.

**Pull request closed without merging**
